export const mockUser = {
  id: "user-123",
  email: "demo@astraflow.com",
  name: "Commander",
  currency: "INR",
  is_verified: true,
};

export const mockState = {
  currency: "INR",
  confirmed_balance: "145000.00",
  unconfirmed_balance: "50000.00",
  total_balance: "195000.00",
  last_updated: new Date().toISOString(),
  obligations: [
    { category: "Housing", average_amount: "65000.00", frequency: "monthly", is_active: true }
  ],
  discretionary_spending: { total: "80000.00" },
  projected_eom_balance: "85000.00",
  health_score: "92.5",
};

export const mockEvents = [
  {
    id: "evt-1",
    title: "Monthly Executive Salary — Infosys Ltd",
    amount: 210000.00,
    direction: "CREDIT",
    date: new Date(Date.now() - 86400000 * 1).toISOString().split("T")[0],
    category: "Salary",
    confidence: 0.99,
    status: "CONFIRMED",
    source: "CSV Import",
    rawEvidence: { snippet: "SALARY CREDIT CORP ACH ID #98231 +210,000.00 CR", verified_at: new Date().toISOString() },
  },
  {
    id: "evt-2",
    title: "Penthouse Apartment Lease — HDFC Auto-Debit",
    amount: 65000.00,
    direction: "DEBIT",
    date: new Date(Date.now() - 86400000 * 3).toISOString().split("T")[0],
    category: "Housing",
    confidence: 0.96,
    status: "CONFIRMED",
    source: "CSV Import",
    rawEvidence: { snippet: "AUTO-DEBIT LEASE PROPERTY MGMT -65,000.00 DR" },
  },
  {
    id: "evt-3",
    title: "Uncategorized Transfer to UPI-INVEST91",
    amount: 50000.00,
    direction: "DEBIT",
    date: new Date(Date.now() - 86400000 * 5).toISOString().split("T")[0],
    category: "Transfers",
    confidence: 0.62,
    status: "UNCERTAIN",
    source: "SMS Import",
    rawEvidence: { snippet: "INR 50,000.00 transferred via UPI to UPI-INVEST91. Ref: TXN8239123" },
  },
  {
    id: "evt-4",
    title: "Whole Foods Market — Grocery Run",
    amount: 8450.50,
    direction: "DEBIT",
    date: new Date(Date.now() - 86400000 * 8).toISOString().split("T")[0],
    category: "Groceries",
    confidence: 0.99,
    status: "CONFIRMED",
    source: "CSV Import",
    rawEvidence: { snippet: "POS DEBIT WHOLE FOODS MARKET -8,450.50 DR" },
  },
  {
    id: "evt-5",
    title: "Freelance Design Work — Client X (Logo Project)",
    amount: 12000.00,
    direction: "CREDIT",
    date: new Date(Date.now() - 86400000 * 1).toISOString().split("T")[0],
    category: "Freelance",
    confidence: 0.95,
    status: "CONFIRMED",
    source: "CSV Import",
    rawEvidence: { snippet: "NEFT TRANSFER - CLIENT X - LOGO DESIGN +12,000.00 CR" },
  },
  {
    id: "evt-6",
    title: "SIP Mutual Fund — Nifty 50 Index",
    amount: 35000.00,
    direction: "DEBIT",
    date: new Date(Date.now() - 86400000 * 10).toISOString().split("T")[0],
    category: "Investments",
    confidence: 0.98,
    status: "CONFIRMED",
    source: "CSV Import",
    rawEvidence: { snippet: "NACH SIP BATCH - UT-NIFTY-50 -35,000.00 DR. Folio: 1234567" },
  },
  {
    id: "evt-7",
    title: "Netflix Premium Subscription",
    amount: 649.00,
    direction: "DEBIT",
    date: new Date(Date.now() - 86400000 * 15).toISOString().split("T")[0],
    category: "Entertainment",
    confidence: 0.99,
    status: "CONFIRMED",
    source: "CSV Import",
    rawEvidence: { snippet: "ACH DEBIT NETFLIX.COM -649.00 DR" },
  },
  {
    id: "evt-8",
    title: "Gold's Gym Annual Membership",
    amount: 15000.00,
    direction: "DEBIT",
    date: new Date(Date.now() - 86400000 * 10).toISOString().split("T")[0],
    category: "Health & Fitness",
    confidence: 0.85,
    status: "LIKELY",
    source: "SMS Import",
    rawEvidence: { snippet: "INR 15,000.00 debited for Gold's Gym on 10-08-2026. Avail Bal: INR 1,95,000" },
  },
  {
    id: "evt-9",
    title: "AWS Cloud Infrastructure Invoice",
    amount: 14200.00,
    direction: "DEBIT",
    date: new Date(Date.now() - 86400000 * 12).toISOString().split("T")[0],
    category: "Tech Infrastructure",
    confidence: 0.94,
    status: "CONFIRMED",
    source: "CSV Import",
    rawEvidence: { snippet: "AWS EMEA HOSTING & CLOUD SVCS -14,200.00 DR. Invoice: AWS-2408-9871" },
  },
  {
    id: "evt-10",
    title: "UI/UX Consulting — RetailCo Project",
    amount: 45000.00,
    direction: "CREDIT",
    date: new Date(Date.now() - 86400000 * 18).toISOString().split("T")[0],
    category: "Consulting",
    confidence: 0.92,
    status: "CONFIRMED",
    source: "CSV Import",
    rawEvidence: { snippet: "INWARD WIRE TXN - RET-CLIENT-AURA +45,000.00 CR" },
  },
  {
    id: "evt-11",
    title: "Zomato Food Delivery — Weekend Orders",
    amount: 3200.00,
    direction: "DEBIT",
    date: new Date(Date.now() - 86400000 * 4).toISOString().split("T")[0],
    category: "Food & Dining",
    confidence: 0.97,
    status: "CONFIRMED",
    source: "SMS Import",
    rawEvidence: { snippet: "INR 3,200.00 paid to Zomato via UPI. Ref: PAY-ZOM-7719123" },
  },
  {
    id: "evt-12",
    title: "Unknown Merchant — Suspicious POS Debit",
    amount: 22500.00,
    direction: "DEBIT",
    date: new Date(Date.now() - 86400000 * 7).toISOString().split("T")[0],
    category: "Uncategorized",
    confidence: 0.40,
    status: "UNCERTAIN",
    source: "SMS Import",
    rawEvidence: { snippet: "INR 22,500 debited from your a/c for POS TXN at MER-XYZ-UNKNWN. Contact bank if not done." },
  },
  {
    id: "evt-13",
    title: "Spotify Premium — Annual Plan",
    amount: 1189.00,
    direction: "DEBIT",
    date: new Date(Date.now() - 86400000 * 20).toISOString().split("T")[0],
    category: "Entertainment",
    confidence: 0.99,
    status: "CONFIRMED",
    source: "CSV Import",
    rawEvidence: { snippet: "ACH DEBIT SPOTIFY AB -1,189.00 DR" },
  },
  {
    id: "evt-14",
    title: "Dividend Credit — Axis Bank Equity Fund",
    amount: 8750.00,
    direction: "CREDIT",
    date: new Date(Date.now() - 86400000 * 22).toISOString().split("T")[0],
    category: "Dividends",
    confidence: 0.88,
    status: "LIKELY",
    source: "CSV Import",
    rawEvidence: { snippet: "DIVIDEND CREDIT AXIS MF +8,750.00 CR. Folio: AX-007-884" },
  },
  {
    id: "evt-15",
    title: "Rejected Duplicate — Duplicate SMS Alert",
    amount: 65000.00,
    direction: "DEBIT",
    date: new Date(Date.now() - 86400000 * 3).toISOString().split("T")[0],
    category: "Housing",
    confidence: 0.30,
    status: "REJECTED",
    source: "SMS Import",
    rawEvidence: { snippet: "[DUPLICATE DETECTED] INR 65,000 lease debit — matches evt-2 within 24h tolerance. Auto-rejected." },
  },
];

export const mockIncomeSources = [
  {
    id: "src-1",
    name: "Primary Tech Salary (Infosys)",
    category: "Salary",
    typical_amount: "210000.00",
    reliability_score: 96.0,
    observation_count: 18,
    is_provisional: false,
    amount_consistency_score: 98.0,
    timeliness_score: 95.0,
    data_confidence_score: 99.0,
  },
  {
    id: "src-2",
    name: "Freelance UI Design",
    category: "Freelance",
    typical_amount: "35000.00",
    reliability_score: 72.0,
    observation_count: 5,
    is_provisional: false,
    amount_consistency_score: 65.0,
    timeliness_score: 60.0,
    data_confidence_score: 85.0,
  },
  {
    id: "src-3",
    name: "Rental Property (Bangalore)",
    category: "Rental",
    typical_amount: "45000.00",
    reliability_score: 88.0,
    observation_count: 12,
    is_provisional: false,
    amount_consistency_score: 100.0,
    timeliness_score: 80.0,
    data_confidence_score: 95.0,
  }
];

export const mockGoals = [
  {
    id: "goal-1",
    name: "Emergency Runway Reserve",
    goal_type: "savings_target",
    target_amount: "500000.00",
    current_amount: "145000.00",
    currency: "INR",
    linked_category: "Rent",
    created_at: new Date().toISOString(),
  }
];

export const mockProvenance = {
  provenanceTree: {
    id: "root",
    type: "balance",
    label: "Confirmed Balance (INR 145,000.00)",
    value: 145000,
    children: [
      {
        id: "evt-1",
        type: "credit",
        label: "Monthly Executive Salary",
        value: 210000,
        children: []
      },
      {
        id: "evt-2",
        type: "debit",
        label: "Penthouse Apartment Lease",
        value: -65000,
        children: []
      }
    ]
  },
  metrics: {
    confirmedEventsCount: 4,
    uncertainEventsCount: 1,
    auditedRatio: "80.0",
    primaryCustodian: "HDFC Bank (Assumed)"
  }
};
